-- v52.48.5.44.8.3
-- 현대건설 흑석9구역 최초계약 182건 -> 91건 안전 정리
-- 서로 다른 source_key의 완전 동일 품목을 정리하고 계약마스터 동기화를 교체방식으로 보강합니다.

begin;

create table if not exists public.progress_contract_items_dedupe_backup (
  backup_id bigint generated by default as identity primary key,
  archived_at timestamptz not null default now(),
  reason text not null,
  contract_item_id text not null,
  contract_version_id text,
  project_name text,
  source_key text,
  row_data jsonb not null
);

drop table if exists pg_temp.cm_semantic_duplicate_map_v524854483;

create temporary table pg_temp.cm_semantic_duplicate_map_v524854483
on commit drop
as
with target_rows as (
  select
    pci.*,
    concat_ws(
      '||',
      lower(regexp_replace(btrim(coalesce(nullif(pci.classification, ''), nullif(pci.housing_type, ''), '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(pci.option_type, '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(nullif(pci.base_item_name, ''), nullif(pci.item_name, ''), '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(pci.specification, '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(pci.unit, '')), '\s+', '', 'g')),
      coalesce(pci.contract_quantity, 0)::text,
      coalesce(pci.contract_material_amount, 0)::text,
      coalesce(pci.contract_labor_amount, 0)::text,
      coalesce(pci.contract_expense_amount, 0)::text
    ) as semantic_key
  from public.progress_contract_items pci
  where pci.contract_version_id = '48a16c0d-2908-4273-9ddc-1f1341ca839b'::uuid
),
new_contract_rows as (
  select *
  from target_rows
  where source_key like 'new-contract:%'
),
semantic_occurrence_rows as (
  select *
  from target_rows
  where source_key ~ '\|.*#[0-9]+$'
)
select
  legacy.id as duplicate_id,
  current_row.id as keep_id,
  current_row.contract_version_id,
  current_row.project_name,
  current_row.semantic_key,
  legacy.source_key as duplicate_source_key,
  current_row.source_key as keep_source_key
from semantic_occurrence_rows legacy
join new_contract_rows current_row
  on current_row.semantic_key = legacy.semantic_key;

do $validate_semantic_cleanup$
declare
  v_target_count integer;
  v_new_contract_count integer;
  v_semantic_occurrence_count integer;
  v_map_count integer;
  v_distinct_keep_count integer;
  v_distinct_duplicate_count integer;
  v_claim_item_count integer;
begin
  select count(*)
    into v_target_count
  from public.progress_contract_items
  where contract_version_id = '48a16c0d-2908-4273-9ddc-1f1341ca839b'::uuid;

  select count(*)
    into v_new_contract_count
  from public.progress_contract_items
  where contract_version_id = '48a16c0d-2908-4273-9ddc-1f1341ca839b'::uuid
    and source_key like 'new-contract:%';

  select count(*)
    into v_semantic_occurrence_count
  from public.progress_contract_items
  where contract_version_id = '48a16c0d-2908-4273-9ddc-1f1341ca839b'::uuid
    and source_key ~ '\|.*#[0-9]+$';

  select
    count(*),
    count(distinct keep_id),
    count(distinct duplicate_id)
  into
    v_map_count,
    v_distinct_keep_count,
    v_distinct_duplicate_count
  from pg_temp.cm_semantic_duplicate_map_v524854483;

  select coalesce(max(item_count), 0)
    into v_claim_item_count
  from public.progress_claims
  where contract_version_id = '48a16c0d-2908-4273-9ddc-1f1341ca839b'::uuid;

  if v_target_count <> 182
     or v_new_contract_count <> 91
     or v_semantic_occurrence_count <> 91
     or v_map_count <> 91
     or v_distinct_keep_count <> 91
     or v_distinct_duplicate_count <> 91
     or v_claim_item_count <> 91
  then
    raise exception
      '안전검증 실패: 전체 %, new-contract %, 기존키 %, 연결쌍 %, keep %, duplicate %, 기성품목 %. 데이터가 진단 당시와 달라 정리를 중단합니다.',
      v_target_count,
      v_new_contract_count,
      v_semantic_occurrence_count,
      v_map_count,
      v_distinct_keep_count,
      v_distinct_duplicate_count,
      v_claim_item_count;
  end if;
end;
$validate_semantic_cleanup$;

insert into public.progress_contract_items_dedupe_backup (
  reason,
  contract_item_id,
  contract_version_id,
  project_name,
  source_key,
  row_data
)
select
  'v52.48.5.44.8.3 semantic duplicate: preserve new-contract key',
  pci.id::text,
  pci.contract_version_id::text,
  pci.project_name,
  pci.source_key,
  to_jsonb(pci)
from public.progress_contract_items pci
join pg_temp.cm_semantic_duplicate_map_v524854483 dm
  on dm.duplicate_id = pci.id;

drop table if exists pg_temp.cm_semantic_merged_mapping_v524854483;

create temporary table pg_temp.cm_semantic_merged_mapping_v524854483
on commit drop
as
with pair_rows as (
  select
    dm.keep_id,
    pci.process_type,
    pci.mapped_by_name,
    pci.mapped_at
  from pg_temp.cm_semantic_duplicate_map_v524854483 dm
  join public.progress_contract_items pci
    on pci.id in (dm.keep_id, dm.duplicate_id)
),
tokens as (
  select
    pr.keep_id,
    btrim(token) as token
  from pair_rows pr
  cross join lateral regexp_split_to_table(
    coalesce(pr.process_type, ''),
    '\s*\+\s*|\s*,\s*'
  ) token
  where btrim(token) <> ''
),
merged_process as (
  select
    keep_id,
    string_agg(distinct token, ' + ' order by token) as process_type
  from tokens
  group by keep_id
),
latest_mapping as (
  select distinct on (keep_id)
    keep_id,
    mapped_by_name,
    mapped_at
  from pair_rows
  where mapped_at is not null
     or btrim(coalesce(mapped_by_name, '')) <> ''
  order by keep_id, mapped_at desc nulls last
)
select
  dm.keep_id,
  mp.process_type,
  lm.mapped_by_name,
  lm.mapped_at
from pg_temp.cm_semantic_duplicate_map_v524854483 dm
left join merged_process mp
  on mp.keep_id = dm.keep_id
left join latest_mapping lm
  on lm.keep_id = dm.keep_id
group by
  dm.keep_id,
  mp.process_type,
  lm.mapped_by_name,
  lm.mapped_at;

update public.progress_contract_items pci
set
  process_type = coalesce(nullif(mm.process_type, ''), pci.process_type),
  mapped_by_name = coalesce(nullif(mm.mapped_by_name, ''), pci.mapped_by_name),
  mapped_at = coalesce(mm.mapped_at, pci.mapped_at)
from pg_temp.cm_semantic_merged_mapping_v524854483 mm
where pci.id = mm.keep_id;

do $fk_repoint$
declare
  v_fk record;
begin
  for v_fk in
    select
      child_ns.nspname as schema_name,
      child.relname as table_name,
      child_col.attname as column_name
    from pg_constraint fk
    join pg_class parent
      on parent.oid = fk.confrelid
    join pg_namespace parent_ns
      on parent_ns.oid = parent.relnamespace
    join pg_class child
      on child.oid = fk.conrelid
    join pg_namespace child_ns
      on child_ns.oid = child.relnamespace
    join pg_attribute child_col
      on child_col.attrelid = fk.conrelid
     and child_col.attnum = fk.conkey[1]
    join pg_attribute parent_col
      on parent_col.attrelid = fk.confrelid
     and parent_col.attnum = fk.confkey[1]
    where fk.contype = 'f'
      and parent_ns.nspname = 'public'
      and parent.relname = 'progress_contract_items'
      and parent_col.attname = 'id'
      and array_length(fk.conkey, 1) = 1
      and array_length(fk.confkey, 1) = 1
  loop
    execute format(
      'update %I.%I child
          set %I = dm.keep_id
         from pg_temp.cm_semantic_duplicate_map_v524854483 dm
        where child.%I::text = dm.duplicate_id::text',
      v_fk.schema_name,
      v_fk.table_name,
      v_fk.column_name,
      v_fk.column_name
    );
  end loop;
end;
$fk_repoint$;

delete from public.progress_contract_items pci
using pg_temp.cm_semantic_duplicate_map_v524854483 dm
where pci.id = dm.duplicate_id;

create unique index if not exists
  ux_progress_contract_items_version_source_key
on public.progress_contract_items (
  contract_version_id,
  btrim(source_key)
)
where source_key is not null
  and btrim(source_key) <> '';

-- 같은 현장/계약버전 재업로드 시 기존 계약품목을 현재 파일로 완전히 교체합니다.
-- exact source_key가 바뀌어도 동일 품목·규격·단위·순번의 기존 공정연결을 이어받습니다.
create or replace function public.sync_progress_contract_master_v1(
  p_project_name text,
  p_contract_version_label text,
  p_effective_date date,
  p_source_file_name text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project_name text := btrim(coalesce(p_project_name, ''));
  v_version_label text := btrim(coalesce(p_contract_version_label, ''));
  v_version_id uuid;
  v_item_count integer := 0;
  v_has_unit_price_columns boolean := false;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if v_project_name = '' then
    raise exception '현장명이 없습니다.';
  end if;

  if v_version_label = '' then
    raise exception '계약버전명이 없습니다.';
  end if;

  if p_items is null
     or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0
  then
    raise exception '동기화할 계약품목이 없습니다.';
  end if;

  perform pg_advisory_xact_lock(
    hashtext(
      'progress_contract_master:' ||
      v_project_name ||
      ':' ||
      v_version_label
    )
  );

  drop table if exists pg_temp.cm_contract_sync_items_v2;
  create temporary table pg_temp.cm_contract_sync_items_v2 (
    source_key text,
    source_row_no integer,
    sort_order integer,
    classification text,
    housing_type text,
    option_type text,
    work_zone text,
    item_name text,
    base_item_name text,
    specification text,
    unit text,
    process_type text,
    contract_quantity numeric,
    material_unit_price numeric,
    labor_unit_price numeric,
    expense_unit_price numeric,
    contract_material_amount numeric,
    contract_labor_amount numeric,
    contract_expense_amount numeric,
    identity_key text,
    identity_occurrence integer
  ) on commit drop;

  insert into pg_temp.cm_contract_sync_items_v2 (
    source_key,
    source_row_no,
    sort_order,
    classification,
    housing_type,
    option_type,
    work_zone,
    item_name,
    base_item_name,
    specification,
    unit,
    process_type,
    contract_quantity,
    material_unit_price,
    labor_unit_price,
    expense_unit_price,
    contract_material_amount,
    contract_labor_amount,
    contract_expense_amount
  )
  select
    btrim(coalesce(x.source_key, '')),
    x.source_row_no,
    x.sort_order,
    btrim(coalesce(x.classification, '')),
    btrim(coalesce(x.housing_type, x.classification, '')),
    btrim(coalesce(x.option_type, '기본')),
    btrim(coalesce(x.work_zone, '')),
    btrim(coalesce(x.item_name, '')),
    btrim(coalesce(x.base_item_name, x.item_name, '')),
    btrim(coalesce(x.specification, '')),
    btrim(coalesce(x.unit, '')),
    btrim(coalesce(x.process_type, '')),
    coalesce(x.contract_quantity, 0),
    coalesce(x.material_unit_price, 0),
    coalesce(x.labor_unit_price, 0),
    coalesce(x.expense_unit_price, 0),
    coalesce(x.contract_material_amount, coalesce(x.contract_quantity, 0) * coalesce(x.material_unit_price, 0)),
    coalesce(x.contract_labor_amount, coalesce(x.contract_quantity, 0) * coalesce(x.labor_unit_price, 0)),
    coalesce(x.contract_expense_amount, coalesce(x.contract_quantity, 0) * coalesce(x.expense_unit_price, 0))
  from jsonb_to_recordset(p_items) as x(
    source_key text,
    source_row_no integer,
    sort_order integer,
    classification text,
    housing_type text,
    option_type text,
    work_zone text,
    item_name text,
    base_item_name text,
    specification text,
    unit text,
    process_type text,
    contract_quantity numeric,
    material_unit_price numeric,
    labor_unit_price numeric,
    expense_unit_price numeric,
    contract_material_amount numeric,
    contract_labor_amount numeric,
    contract_expense_amount numeric
  );

  delete from pg_temp.cm_contract_sync_items_v2
  where source_key = ''
     or item_name = '';

  if exists (
    select 1
    from pg_temp.cm_contract_sync_items_v2
    group by source_key
    having count(*) > 1
  ) then
    raise exception '표준양식에 동일한 SYSTEM_ITEM_KEY가 중복되어 있습니다.';
  end if;

  update pg_temp.cm_contract_sync_items_v2
  set identity_key = concat_ws(
    '||',
    lower(regexp_replace(classification, '\s+', '', 'g')),
    lower(regexp_replace(option_type, '\s+', '', 'g')),
    lower(regexp_replace(base_item_name, '\s+', '', 'g')),
    lower(regexp_replace(specification, '\s+', '', 'g')),
    lower(regexp_replace(unit, '\s+', '', 'g'))
  );

  with ranked as (
    select
      ctid,
      row_number() over (
        partition by identity_key
        order by sort_order nulls last, source_row_no nulls last, source_key
      ) as occurrence
    from pg_temp.cm_contract_sync_items_v2
  )
  update pg_temp.cm_contract_sync_items_v2 target
  set identity_occurrence = ranked.occurrence
  from ranked
  where target.ctid = ranked.ctid;

  select count(*)
    into v_item_count
  from pg_temp.cm_contract_sync_items_v2;

  if v_item_count = 0 then
    raise exception '유효한 계약품목이 없습니다.';
  end if;

  select pcv.id
    into v_version_id
  from public.progress_contract_versions pcv
  where btrim(pcv.project_name) = v_project_name
    and btrim(pcv.version_label) = v_version_label
  order by pcv.created_at desc nulls last
  limit 1
  for update;

  if v_version_id is null then
    insert into public.progress_contract_versions (
      project_name,
      version_label,
      effective_date,
      source_file_name
    )
    values (
      v_project_name,
      v_version_label,
      p_effective_date,
      nullif(btrim(coalesce(p_source_file_name, '')), '')
    )
    returning id into v_version_id;
  else
    update public.progress_contract_versions
    set
      effective_date = coalesce(p_effective_date, effective_date),
      source_file_name = coalesce(
        nullif(btrim(coalesce(p_source_file_name, '')), ''),
        source_file_name
      )
    where id = v_version_id;
  end if;

  drop table if exists pg_temp.cm_contract_existing_mapping_v2;
  create temporary table pg_temp.cm_contract_existing_mapping_v2
  on commit drop
  as
  with existing_ranked as (
    select
      btrim(coalesce(pci.source_key, '')) as source_key,
      concat_ws(
        '||',
        lower(regexp_replace(btrim(coalesce(nullif(pci.classification, ''), nullif(pci.housing_type, ''), '')), '\s+', '', 'g')),
        lower(regexp_replace(btrim(coalesce(pci.option_type, '')), '\s+', '', 'g')),
        lower(regexp_replace(btrim(coalesce(nullif(pci.base_item_name, ''), nullif(pci.item_name, ''), '')), '\s+', '', 'g')),
        lower(regexp_replace(btrim(coalesce(pci.specification, '')), '\s+', '', 'g')),
        lower(regexp_replace(btrim(coalesce(pci.unit, '')), '\s+', '', 'g'))
      ) as identity_key,
      row_number() over (
        partition by concat_ws(
          '||',
          lower(regexp_replace(btrim(coalesce(nullif(pci.classification, ''), nullif(pci.housing_type, ''), '')), '\s+', '', 'g')),
          lower(regexp_replace(btrim(coalesce(pci.option_type, '')), '\s+', '', 'g')),
          lower(regexp_replace(btrim(coalesce(nullif(pci.base_item_name, ''), nullif(pci.item_name, ''), '')), '\s+', '', 'g')),
          lower(regexp_replace(btrim(coalesce(pci.specification, '')), '\s+', '', 'g')),
          lower(regexp_replace(btrim(coalesce(pci.unit, '')), '\s+', '', 'g'))
        )
        order by pci.sort_order nulls last, pci.source_row_no nulls last, pci.id::text
      ) as identity_occurrence,
      pci.process_type,
      pci.mapped_by_name,
      pci.mapped_at
    from public.progress_contract_items pci
    where pci.contract_version_id = v_version_id
  )
  select * from existing_ranked;

  delete from public.progress_contract_items
  where contract_version_id = v_version_id;

  select
    exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'progress_contract_items'
        and column_name = 'material_unit_price'
    )
    and exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'progress_contract_items'
        and column_name = 'labor_unit_price'
    )
    and exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'progress_contract_items'
        and column_name = 'expense_unit_price'
    )
  into v_has_unit_price_columns;

  if v_has_unit_price_columns then
    insert into public.progress_contract_items (
      contract_version_id,
      project_name,
      source_key,
      source_row_no,
      sort_order,
      classification,
      housing_type,
      option_type,
      work_zone,
      item_name,
      base_item_name,
      specification,
      unit,
      process_type,
      contract_quantity,
      material_unit_price,
      labor_unit_price,
      expense_unit_price,
      contract_material_amount,
      contract_labor_amount,
      contract_expense_amount,
      mapped_by_name,
      mapped_at
    )
    select
      v_version_id,
      v_project_name,
      s.source_key,
      s.source_row_no,
      s.sort_order,
      s.classification,
      case when s.classification <> '' then s.classification else s.housing_type end,
      s.option_type,
      s.work_zone,
      s.item_name,
      s.base_item_name,
      s.specification,
      s.unit,
      coalesce(nullif(me.process_type, ''), nullif(mf.process_type, ''), nullif(s.process_type, ''), ''),
      s.contract_quantity,
      s.material_unit_price,
      s.labor_unit_price,
      s.expense_unit_price,
      s.contract_material_amount,
      s.contract_labor_amount,
      s.contract_expense_amount,
      coalesce(nullif(me.mapped_by_name, ''), nullif(mf.mapped_by_name, '')),
      coalesce(me.mapped_at, mf.mapped_at)
    from pg_temp.cm_contract_sync_items_v2 s
    left join pg_temp.cm_contract_existing_mapping_v2 me
      on me.source_key = s.source_key
    left join pg_temp.cm_contract_existing_mapping_v2 mf
      on mf.identity_key = s.identity_key
     and mf.identity_occurrence = s.identity_occurrence
    order by s.sort_order, s.source_row_no;
  else
    insert into public.progress_contract_items (
      contract_version_id,
      project_name,
      source_key,
      source_row_no,
      sort_order,
      classification,
      housing_type,
      option_type,
      work_zone,
      item_name,
      base_item_name,
      specification,
      unit,
      process_type,
      contract_quantity,
      contract_material_amount,
      contract_labor_amount,
      contract_expense_amount,
      mapped_by_name,
      mapped_at
    )
    select
      v_version_id,
      v_project_name,
      s.source_key,
      s.source_row_no,
      s.sort_order,
      s.classification,
      case when s.classification <> '' then s.classification else s.housing_type end,
      s.option_type,
      s.work_zone,
      s.item_name,
      s.base_item_name,
      s.specification,
      s.unit,
      coalesce(nullif(me.process_type, ''), nullif(mf.process_type, ''), nullif(s.process_type, ''), ''),
      s.contract_quantity,
      s.contract_material_amount,
      s.contract_labor_amount,
      s.contract_expense_amount,
      coalesce(nullif(me.mapped_by_name, ''), nullif(mf.mapped_by_name, '')),
      coalesce(me.mapped_at, mf.mapped_at)
    from pg_temp.cm_contract_sync_items_v2 s
    left join pg_temp.cm_contract_existing_mapping_v2 me
      on me.source_key = s.source_key
    left join pg_temp.cm_contract_existing_mapping_v2 mf
      on mf.identity_key = s.identity_key
     and mf.identity_occurrence = s.identity_occurrence
    order by s.sort_order, s.source_row_no;
  end if;

  return jsonb_build_object(
    'project_name', v_project_name,
    'contract_version_id', v_version_id,
    'contract_version_label', v_version_label,
    'item_count', v_item_count,
    'process_mapping_preserved', true,
    'replace_mode', true,
    'semantic_mapping_fallback', true,
    'duplicate_guard', true,
    'sync_lock', true
  );
end;
$$;

revoke all on function public.sync_progress_contract_master_v1(
  text,
  text,
  date,
  text,
  jsonb
) from public;

grant execute on function public.sync_progress_contract_master_v1(
  text,
  text,
  date,
  text,
  jsonb
) to authenticated;

commit;

-- 최종 결과: contract_item_count=91, distinct_source_key_count=91,
-- semantic_item_count=91, remaining_semantic_duplicate_rows=0이어야 정상입니다.
with target as (
  select
    pci.*,
    concat_ws(
      '||',
      lower(regexp_replace(btrim(coalesce(nullif(pci.classification, ''), nullif(pci.housing_type, ''), '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(pci.option_type, '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(nullif(pci.base_item_name, ''), nullif(pci.item_name, ''), '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(pci.specification, '')), '\s+', '', 'g')),
      lower(regexp_replace(btrim(coalesce(pci.unit, '')), '\s+', '', 'g')),
      coalesce(pci.contract_quantity, 0)::text,
      coalesce(pci.contract_material_amount, 0)::text,
      coalesce(pci.contract_labor_amount, 0)::text,
      coalesce(pci.contract_expense_amount, 0)::text
    ) as semantic_key
  from public.progress_contract_items pci
  where pci.contract_version_id = '48a16c0d-2908-4273-9ddc-1f1341ca839b'::uuid
),
semantic_groups as (
  select semantic_key, count(*) as group_count
  from target
  group by semantic_key
)
select
  count(*) as contract_item_count,
  count(distinct nullif(btrim(source_key), '')) as distinct_source_key_count,
  (select count(*) from semantic_groups) as semantic_item_count,
  (
    select coalesce(sum(group_count - 1), 0)
    from semantic_groups
    where group_count > 1
  ) as remaining_semantic_duplicate_rows,
  count(*) filter (where source_key like 'new-contract:%') as new_contract_item_count,
  count(*) filter (where btrim(coalesce(process_type, '')) <> '') as mapped_item_count,
  (
    select count(*)
    from public.progress_contract_items_dedupe_backup
    where reason = 'v52.48.5.44.8.3 semantic duplicate: preserve new-contract key'
      and contract_version_id = '48a16c0d-2908-4273-9ddc-1f1341ca839b'
  ) as backup_row_count
from target;
