-- v52.48.5.44.8.2
-- 계약품목 공정연결 중복 정리 + 재발 방지

create table if not exists public.progress_contract_items_dedupe_backup (
  backup_id bigint generated by default as identity primary key,
  archived_at timestamptz not null default now(),
  reason text not null,
  contract_item_id text not null,
  contract_version_id text,
  project_name text,
  source_key text,
  row_data jsonb not null
);

drop table if exists pg_temp.cm_contract_duplicate_map;

create temporary table pg_temp.cm_contract_duplicate_map
on commit drop
as
with ranked as (
  select
    pci.id,
    pci.contract_version_id,
    btrim(coalesce(pci.source_key, '')) as normalized_source_key,
    row_number() over (
      partition by
        pci.contract_version_id,
        btrim(coalesce(pci.source_key, ''))
      order by
        case
          when btrim(coalesce(pci.process_type, '')) <> '' then 0
          else 1
        end,
        pci.mapped_at desc nulls last,
        pci.sort_order asc nulls last,
        pci.source_row_no asc nulls last,
        pci.id::text asc
    ) as rn
  from public.progress_contract_items pci
  where btrim(coalesce(pci.source_key, '')) <> ''
),
keepers as (
  select
    contract_version_id,
    normalized_source_key,
    id as keep_id
  from ranked
  where rn = 1
)
select
  r.id as duplicate_id,
  k.keep_id,
  r.contract_version_id,
  r.normalized_source_key
from ranked r
join keepers k
  on k.contract_version_id = r.contract_version_id
 and k.normalized_source_key = r.normalized_source_key
where r.rn > 1;

insert into public.progress_contract_items_dedupe_backup (
  reason,
  contract_item_id,
  contract_version_id,
  project_name,
  source_key,
  row_data
)
select
  'v52.48.5.44.8.2 duplicate contract_version_id + source_key',
  pci.id::text,
  pci.contract_version_id::text,
  pci.project_name,
  pci.source_key,
  to_jsonb(pci)
from public.progress_contract_items pci
join pg_temp.cm_contract_duplicate_map dm
  on dm.duplicate_id = pci.id;

drop table if exists pg_temp.cm_contract_merged_mapping;

create temporary table pg_temp.cm_contract_merged_mapping
on commit drop
as
with duplicate_groups as (
  select distinct
    dm.keep_id,
    dm.contract_version_id,
    dm.normalized_source_key
  from pg_temp.cm_contract_duplicate_map dm
),
group_rows as (
  select
    dg.keep_id,
    pci.process_type,
    pci.mapped_by_name,
    pci.mapped_at
  from duplicate_groups dg
  join public.progress_contract_items pci
    on pci.contract_version_id = dg.contract_version_id
   and btrim(coalesce(pci.source_key, '')) = dg.normalized_source_key
),
tokens as (
  select
    gr.keep_id,
    btrim(token) as token
  from group_rows gr
  cross join lateral regexp_split_to_table(
    coalesce(gr.process_type, ''),
    '\s*\+\s*|\s*,\s*'
  ) token
  where btrim(token) <> ''
),
merged_process as (
  select
    keep_id,
    string_agg(
      distinct token,
      ' + '
      order by token
    ) as process_type
  from tokens
  group by keep_id
),
latest_mapping as (
  select distinct on (keep_id)
    keep_id,
    mapped_by_name,
    mapped_at
  from group_rows
  where mapped_at is not null
     or btrim(coalesce(mapped_by_name, '')) <> ''
  order by
    keep_id,
    mapped_at desc nulls last
)
select
  dg.keep_id,
  mp.process_type,
  lm.mapped_by_name,
  lm.mapped_at
from duplicate_groups dg
left join merged_process mp
  on mp.keep_id = dg.keep_id
left join latest_mapping lm
  on lm.keep_id = dg.keep_id;

update public.progress_contract_items pci
set
  process_type = coalesce(
    nullif(mm.process_type, ''),
    pci.process_type
  ),
  mapped_by_name = coalesce(
    nullif(mm.mapped_by_name, ''),
    pci.mapped_by_name
  ),
  mapped_at = coalesce(
    mm.mapped_at,
    pci.mapped_at
  )
from pg_temp.cm_contract_merged_mapping mm
where pci.id = mm.keep_id;

do $fk_repoint$
declare
  v_fk record;
begin
  for v_fk in
    select
      child_ns.nspname as schema_name,
      child.relname as table_name,
      child_col.attname as column_name
    from pg_constraint fk
    join pg_class parent
      on parent.oid = fk.confrelid
    join pg_namespace parent_ns
      on parent_ns.oid = parent.relnamespace
    join pg_class child
      on child.oid = fk.conrelid
    join pg_namespace child_ns
      on child_ns.oid = child.relnamespace
    join pg_attribute child_col
      on child_col.attrelid = fk.conrelid
     and child_col.attnum = fk.conkey[1]
    join pg_attribute parent_col
      on parent_col.attrelid = fk.confrelid
     and parent_col.attnum = fk.confkey[1]
    where fk.contype = 'f'
      and parent_ns.nspname = 'public'
      and parent.relname = 'progress_contract_items'
      and parent_col.attname = 'id'
      and array_length(fk.conkey, 1) = 1
      and array_length(fk.confkey, 1) = 1
  loop
    execute format(
      'update %I.%I child
          set %I = dm.keep_id
         from pg_temp.cm_contract_duplicate_map dm
        where child.%I::text = dm.duplicate_id::text',
      v_fk.schema_name,
      v_fk.table_name,
      v_fk.column_name,
      v_fk.column_name
    );
  end loop;
end;
$fk_repoint$;

delete from public.progress_contract_items pci
using pg_temp.cm_contract_duplicate_map dm
where pci.id = dm.duplicate_id;

create unique index if not exists
  ux_progress_contract_items_version_source_key
on public.progress_contract_items (
  contract_version_id,
  btrim(source_key)
)
where source_key is not null
  and btrim(source_key) <> '';

-- DB 재발 방지의 핵심은 위 UNIQUE INDEX입니다.
-- 현재 sync_progress_contract_master_v1도 업로드 JSON 내부 source_key 중복을
-- 이미 오류 처리하고 있으므로, DB UNIQUE INDEX까지 더해 같은 계약버전/source_key
-- 중복 저장을 차단합니다.

select
  count(*) as duplicate_group_count,
  coalesce(sum(group_count - 1), 0) as remaining_duplicate_rows
from (
  select
    contract_version_id,
    btrim(source_key) as source_key,
    count(*) as group_count
  from public.progress_contract_items
  where btrim(coalesce(source_key, '')) <> ''
  group by
    contract_version_id,
    btrim(source_key)
  having count(*) > 1
) duplicate_groups;
