begin;

create extension if not exists pgcrypto;

create table if not exists public.departments (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  organization_type text not null default '공통'
    check (organization_type in ('공통', '본사', '현장', '외부업체')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.permission_definitions (
  permission_key text primary key,
  area_code text not null,
  menu_code text not null,
  action_code text not null,
  action_label text not null,
  action_rank integer not null default 10,
  is_sensitive boolean not null default false,
  created_at timestamptz not null default now(),
  unique (menu_code, action_code)
);

create table if not exists public.permission_templates (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  organization_type text not null
    check (organization_type in ('공통', '본사', '현장', '외부업체')),
  department_code text references public.departments(code),
  description text not null default '',
  sort_order integer not null default 0,
  is_system boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.template_menu_levels (
  template_code text not null references public.permission_templates(code) on delete cascade,
  menu_code text not null,
  permission_level text not null
    check (permission_level in ('조회', '작성', '관리', '결재')),
  level_rank integer not null
    check (level_rank in (10, 25, 50, 70)),
  primary key (template_code, menu_code)
);

create table if not exists public.template_permissions (
  template_code text not null references public.permission_templates(code) on delete cascade,
  permission_key text not null references public.permission_definitions(permission_key) on delete cascade,
  is_granted boolean not null default true,
  primary key (template_code, permission_key)
);

create table if not exists public.user_access_settings_v2 (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  organization_type text not null default '현장'
    check (organization_type in ('본사', '현장', '외부업체')),
  department_code text not null references public.departments(code),
  permission_template_code text not null references public.permission_templates(code),
  access_scope text not null default 'selected'
    check (access_scope in ('home_project', 'selected', 'all')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.user_project_access_v2 (
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  project_name text not null,
  access_start_date date,
  access_end_date date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (auth_user_id, project_name),
  check (access_end_date is null or access_start_date is null or access_end_date >= access_start_date)
);

create table if not exists public.user_access_audit_log_v2 (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  changed_by uuid references auth.users(id),
  before_value jsonb,
  after_value jsonb,
  changed_at timestamptz not null default now()
);

create index if not exists idx_user_project_access_v2_project
  on public.user_project_access_v2(project_name, auth_user_id)
  where is_active = true;

create index if not exists idx_user_access_audit_v2_target
  on public.user_access_audit_log_v2(target_user_id, changed_at desc);

insert into public.departments (code, name, organization_type, sort_order)
values
  ('construction', '공사', '공통', 10),
  ('safety', '안전', '공통', 20),
  ('administration', '관리', '공통', 30),
  ('material', '자재', '공통', 40),
  ('subcontract', '외주', '공통', 50),
  ('external', '외부업체', '외부업체', 90)
on conflict (code) do update
set name = excluded.name,
    organization_type = excluded.organization_type,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

insert into public.permission_templates
  (code, name, organization_type, department_code, description, sort_order)
values
  ('super_admin', '최고관리자', '공통', null, '전체현장과 모든 기능을 관리합니다.', 1),
  ('hq_construction', '본사 공사담당', '본사', 'construction', '공정·일보·도면을 중심으로 선택현장을 관리합니다.', 10),
  ('hq_safety', '본사 안전담당', '본사', 'safety', '안전관리와 사고자료를 중심으로 선택현장을 관리합니다.', 20),
  ('hq_administration', '본사 관리담당', '본사', 'administration', '조직·노임·지출 자료를 중심으로 관리합니다.', 30),
  ('hq_material', '본사 자재담당', '본사', 'material', '자재발주와 자재투입 자료를 관리합니다.', 40),
  ('hq_subcontract', '본사 외주담당', '본사', 'subcontract', '기성·계약·외주 품의 자료를 관리합니다.', 50),
  ('site_manager', '현장소장', '현장', 'construction', '소속현장의 업무를 관리하고 지정 결재를 처리합니다.', 60),
  ('site_construction', '현장 공사담당', '현장', 'construction', '소속현장의 일보·공정·도면 업무를 작성합니다.', 70),
  ('site_safety', '현장 안전담당', '현장', 'safety', '소속현장의 안전관리와 사고자료를 작성합니다.', 80),
  ('site_administration', '현장 관리담당', '현장', 'administration', '소속현장의 노임·지출·관리 업무를 작성합니다.', 90),
  ('external_partner', '외부업체', '외부업체', 'external', '지정된 현장·기간·기능만 사용합니다.', 100)
on conflict (code) do update
set name = excluded.name,
    organization_type = excluded.organization_type,
    department_code = excluded.department_code,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

insert into public.permission_definitions
  (permission_key, area_code, menu_code, action_code, action_label, action_rank, is_sensitive)
values
  ('construction.dashboard.view', 'construction', 'dashboard', 'view', '조회', 10, false),
  ('construction.dashboard.manage', 'construction', 'dashboard', 'manage', '일정관리', 50, false),
  ('common.main.view', 'common', 'main', 'view', '조회', 10, false),
  ('common.main.notice_manage', 'common', 'main', 'notice_manage', '공지관리', 90, true),
  ('common.organization.view', 'common', 'organization', 'view', '조회', 10, false),
  ('common.organization.manage', 'common', 'organization', 'manage', '조직도관리', 50, false),
  ('system.user_management.view', 'system', 'user_management', 'view', '조회', 10, true),
  ('system.user_management.manage', 'system', 'user_management', 'manage', '회원·권한관리', 90, true),
  ('approval.inbox.view', 'approval', 'approval_inbox', 'view', '조회', 10, false),
  ('approval.inbox.approve', 'approval', 'approval_inbox', 'approve', '승인·반려', 70, false),
  ('approval.inbox.download', 'approval', 'approval_inbox', 'download', '다운로드', 20, false),
  ('approval.inbox.force_delete', 'approval', 'approval_inbox', 'force_delete', '강제삭제', 90, true),
  ('construction.weekly_overview.view', 'construction', 'weekly_overview', 'view', '조회', 10, false),
  ('construction.weekly_overview.create', 'construction', 'weekly_overview', 'create', '작성', 20, false),
  ('construction.weekly_overview.edit', 'construction', 'weekly_overview', 'edit', '수정', 30, false),
  ('construction.weekly_overview.delete', 'construction', 'weekly_overview', 'delete', '삭제', 40, false),
  ('construction.weekly_overview.download', 'construction', 'weekly_overview', 'download', '다운로드', 20, false),
  ('construction.daily_report.view', 'construction', 'daily_report', 'view', '조회', 10, false),
  ('construction.daily_report.create', 'construction', 'daily_report', 'create', '작성', 20, false),
  ('construction.daily_report.edit', 'construction', 'daily_report', 'edit', '수정', 30, false),
  ('construction.daily_report.delete', 'construction', 'daily_report', 'delete', '삭제', 40, false),
  ('construction.daily_report.download', 'construction', 'daily_report', 'download', '다운로드', 20, false),
  ('construction.daily_report.close', 'construction', 'daily_report', 'close', '마감', 70, false),
  ('construction.daily_report.reopen', 'construction', 'daily_report', 'reopen', '마감취소', 90, true),
  ('construction.daily_report.historical_upload', 'construction', 'daily_report', 'historical_upload', '과거일보 업로드', 50, false),
  ('construction.progress.view', 'construction', 'progress', 'view', '조회', 10, false),
  ('construction.progress.create', 'construction', 'progress', 'create', '작성', 20, false),
  ('construction.progress.edit', 'construction', 'progress', 'edit', '수정', 30, false),
  ('construction.progress.delete', 'construction', 'progress', 'delete', '삭제', 40, false),
  ('construction.progress.download', 'construction', 'progress', 'download', '다운로드', 20, false),
  ('construction.drawing.view', 'construction', 'drawing', 'view', '조회', 10, false),
  ('construction.drawing.edit', 'construction', 'drawing', 'edit', '수정', 30, false),
  ('construction.drawing.replace_source', 'construction', 'drawing', 'replace_source', 'DXF·기준자료 교체', 90, true),
  ('material.order.view', 'material', 'material_order', 'view', '조회', 10, false),
  ('material.order.create', 'material', 'material_order', 'create', '작성', 20, false),
  ('material.order.edit', 'material', 'material_order', 'edit', '수정', 30, false),
  ('material.order.delete', 'material', 'material_order', 'delete', '삭제', 40, false),
  ('material.order.submit', 'material', 'material_order', 'submit', '결재요청', 30, false),
  ('material.order.download', 'material', 'material_order', 'download', '다운로드', 20, false),
  ('material.input.view', 'material', 'material_input', 'view', '조회', 10, false),
  ('material.input.create', 'material', 'material_input', 'create', '업로드·작성', 20, false),
  ('material.input.edit', 'material', 'material_input', 'edit', '수정', 30, false),
  ('material.input.download', 'material', 'material_input', 'download', '다운로드', 20, false),
  ('material.input.replace_ledger', 'material', 'material_input', 'replace_ledger', '원장교체', 90, true),
  ('claim.statement.view', 'claim', 'claim_statement', 'view', '조회', 10, false),
  ('claim.statement.create', 'claim', 'claim_statement', 'create', '작성', 20, false),
  ('claim.statement.edit', 'claim', 'claim_statement', 'edit', '수정', 30, false),
  ('claim.statement.complete', 'claim', 'claim_statement', 'complete', '작성완료·작성수정', 90, true),
  ('claim.process_link.view', 'claim', 'claim_process_link', 'view', '조회', 10, false),
  ('claim.process_link.edit', 'claim', 'claim_process_link', 'edit', '연결·해제', 30, false),
  ('labor.contract.view', 'labor', 'labor_contract', 'view', '조회', 10, false),
  ('labor.contract.create', 'labor', 'labor_contract', 'create', '작성', 20, false),
  ('labor.contract.edit', 'labor', 'labor_contract', 'edit', '수정', 30, false),
  ('labor.contract.delete', 'labor', 'labor_contract', 'delete', '삭제', 40, false),
  ('labor.contract.download', 'labor', 'labor_contract', 'download', '다운로드', 20, false),
  ('labor.contract.personal_view', 'labor', 'labor_contract', 'personal_view', '개인정보 조회', 90, true),
  ('labor.contract.personal_export', 'labor', 'labor_contract', 'personal_export', '개인정보 PDF·다운로드', 90, true),
  ('labor.cost.view', 'labor', 'labor_cost', 'view', '조회', 10, false),
  ('labor.cost.create', 'labor', 'labor_cost', 'create', '작성', 20, false),
  ('labor.cost.edit', 'labor', 'labor_cost', 'edit', '수정', 30, false),
  ('labor.cost.delete', 'labor', 'labor_cost', 'delete', '삭제', 40, false),
  ('labor.cost.download', 'labor', 'labor_cost', 'download', '다운로드', 20, false),
  ('labor.cost.manage_rates', 'labor', 'labor_cost', 'manage_rates', '단가이력관리', 50, false),
  ('labor.cost.purge', 'labor', 'labor_cost', 'purge', '전체삭제', 90, true),
  ('report.weekly.view', 'report', 'weekly_report', 'view', '조회', 10, false),
  ('report.weekly.create', 'report', 'weekly_report', 'create', '작성', 20, false),
  ('report.weekly.edit', 'report', 'weekly_report', 'edit', '수정', 30, false),
  ('report.weekly.submit', 'report', 'weekly_report', 'submit', '결재요청', 30, false),
  ('report.weekly.download', 'report', 'weekly_report', 'download', '다운로드', 20, false),
  ('report.expense.view', 'report', 'expense_resolution', 'view', '조회', 10, false),
  ('report.expense.create', 'report', 'expense_resolution', 'create', '작성', 20, false),
  ('report.expense.edit', 'report', 'expense_resolution', 'edit', '수정', 30, false),
  ('report.expense.delete', 'report', 'expense_resolution', 'delete', '삭제', 40, false),
  ('report.expense.download', 'report', 'expense_resolution', 'download', '다운로드', 20, false),
  ('report.proposal.view', 'report', 'proposal_report', 'view', '조회', 10, false),
  ('report.proposal.create', 'report', 'proposal_report', 'create', '작성', 20, false),
  ('report.proposal.edit', 'report', 'proposal_report', 'edit', '수정', 30, false),
  ('report.proposal.delete', 'report', 'proposal_report', 'delete', '삭제', 40, false),
  ('report.proposal.submit', 'report', 'proposal_report', 'submit', '결재요청', 30, false),
  ('report.proposal.download', 'report', 'proposal_report', 'download', '다운로드', 20, false),
  ('safety.incident.view', 'safety', 'incident_report', 'view', '조회', 10, true),
  ('safety.incident.create', 'safety', 'incident_report', 'create', '작성', 20, true),
  ('safety.incident.edit', 'safety', 'incident_report', 'edit', '수정', 30, true),
  ('safety.incident.delete', 'safety', 'incident_report', 'delete', '삭제', 40, true),
  ('safety.incident.submit', 'safety', 'incident_report', 'submit', '결재요청', 30, true),
  ('safety.incident.download', 'safety', 'incident_report', 'download', '다운로드', 90, true),
  ('system.all_projects.view', 'system', 'all_projects', 'view', '전체현장 조회', 90, true),
  ('system.data.purge', 'system', 'system_data', 'purge', '전체 데이터 삭제·초기화', 90, true)
on conflict (permission_key) do update
set area_code = excluded.area_code,
    menu_code = excluded.menu_code,
    action_code = excluded.action_code,
    action_label = excluded.action_label,
    action_rank = excluded.action_rank,
    is_sensitive = excluded.is_sensitive;

with template_levels(template_code, permission_level, level_rank, menu_codes) as (
  values
    ('hq_construction', '관리', 50, array['dashboard','weekly_overview','progress','drawing']::text[]),
    ('hq_construction', '조회', 10, array['main','organization','daily_report','material_order','material_input','claim_statement','claim_process_link','labor_contract','labor_cost','incident_report']::text[]),
    ('hq_construction', '작성', 25, array['weekly_report','expense_resolution','proposal_report']::text[]),
    ('hq_safety', '관리', 50, array['incident_report']::text[]),
    ('hq_safety', '조회', 10, array['dashboard','main','organization','daily_report','progress','weekly_overview']::text[]),
    ('hq_safety', '작성', 25, array['weekly_report','expense_resolution','proposal_report']::text[]),
    ('hq_administration', '관리', 50, array['organization','labor_contract','labor_cost','expense_resolution']::text[]),
    ('hq_administration', '조회', 10, array['dashboard','main','approval_inbox','weekly_overview','daily_report','progress','material_order','material_input','claim_statement','incident_report']::text[]),
    ('hq_administration', '작성', 25, array['weekly_report','proposal_report']::text[]),
    ('hq_material', '관리', 50, array['material_order','material_input']::text[]),
    ('hq_material', '조회', 10, array['dashboard','main','organization','daily_report','progress','claim_statement']::text[]),
    ('hq_material', '작성', 25, array['weekly_report','expense_resolution','proposal_report']::text[]),
    ('hq_subcontract', '관리', 50, array['claim_statement','claim_process_link','proposal_report']::text[]),
    ('hq_subcontract', '조회', 10, array['dashboard','main','organization','daily_report','progress','drawing','material_order','material_input','labor_contract','labor_cost']::text[]),
    ('hq_subcontract', '작성', 25, array['weekly_report','expense_resolution']::text[]),
    ('site_manager', '결재', 70, array['approval_inbox','weekly_report','expense_resolution','proposal_report','incident_report']::text[]),
    ('site_manager', '관리', 50, array['dashboard','weekly_overview','daily_report','progress','drawing','material_order','material_input','claim_statement','claim_process_link','labor_contract','labor_cost']::text[]),
    ('site_manager', '조회', 10, array['main','organization']::text[]),
    ('site_construction', '관리', 50, array['daily_report','progress']::text[]),
    ('site_construction', '작성', 25, array['weekly_overview','drawing','material_order','material_input','claim_statement','claim_process_link','labor_contract','labor_cost','weekly_report','expense_resolution','proposal_report']::text[]),
    ('site_construction', '조회', 10, array['dashboard','main','organization','incident_report']::text[]),
    ('site_safety', '관리', 50, array['incident_report']::text[]),
    ('site_safety', '작성', 25, array['weekly_overview','weekly_report','expense_resolution','proposal_report']::text[]),
    ('site_safety', '조회', 10, array['dashboard','main','organization','daily_report','progress','drawing']::text[]),
    ('site_administration', '관리', 50, array['labor_contract','labor_cost','expense_resolution']::text[]),
    ('site_administration', '작성', 25, array['weekly_overview','daily_report','material_order','material_input','claim_statement','claim_process_link','weekly_report','proposal_report','incident_report']::text[]),
    ('site_administration', '조회', 10, array['dashboard','main','organization','progress','drawing']::text[]),
    ('external_partner', '작성', 25, array['daily_report','progress','material_input']::text[]),
    ('external_partner', '조회', 10, array['main','drawing']::text[])
), expanded as (
  select template_code, permission_level, level_rank, unnest(menu_codes) as menu_code
  from template_levels
)
insert into public.template_menu_levels
  (template_code, menu_code, permission_level, level_rank)
select template_code, menu_code, permission_level, level_rank
from expanded
on conflict (template_code, menu_code) do update
set permission_level = excluded.permission_level,
    level_rank = excluded.level_rank;

delete from public.template_permissions
where template_code in (
  'super_admin',
  'hq_construction',
  'hq_safety',
  'hq_administration',
  'hq_material',
  'hq_subcontract',
  'site_manager',
  'site_construction',
  'site_safety',
  'site_administration',
  'external_partner'
);

insert into public.template_permissions (template_code, permission_key, is_granted)
select t.code, p.permission_key, true
from public.permission_templates t
cross join public.permission_definitions p
where t.code = 'super_admin'
union all
select l.template_code, p.permission_key, true
from public.template_menu_levels l
join public.permission_definitions p
  on p.menu_code = l.menu_code
 and p.action_rank <= l.level_rank
 and p.is_sensitive = false
on conflict (template_code, permission_key) do update
set is_granted = excluded.is_granted;

create or replace function public.permission_phase2_is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_profiles up
    where up.auth_user_id = auth.uid()
      and coalesce(lower(trim(up.account_status)), 'active') = 'active'
      and lower(regexp_replace(coalesce(up.role, ''), '[[:space:]_-]+', '', 'g'))
        in ('최고관리자', 'superadmin', 'masteradmin')
  );
$$;

create or replace function public.admin_get_access_catalog_v2()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.permission_phase2_is_super_admin() then
    raise exception '최고관리자만 권한 기준정보를 조회할 수 있습니다.';
  end if;

  return jsonb_build_object(
    'departments', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'code', d.code,
        'name', d.name,
        'organization_type', d.organization_type,
        'sort_order', d.sort_order
      ) order by d.sort_order, d.name), '[]'::jsonb)
      from public.departments d
      where d.is_active = true
    ),
    'templates', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'code', t.code,
        'name', t.name,
        'organization_type', t.organization_type,
        'department_code', t.department_code,
        'description', t.description,
        'sort_order', t.sort_order
      ) order by t.sort_order, t.name), '[]'::jsonb)
      from public.permission_templates t
      where t.is_active = true
    )
  );
end;
$$;

create or replace function public.admin_list_user_access_v2()
returns table (
  auth_user_id uuid,
  organization_type text,
  department_code text,
  department_name text,
  permission_template_code text,
  permission_template_name text,
  access_scope text,
  project_access jsonb
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.permission_phase2_is_super_admin() then
    raise exception '최고관리자만 회원 권한설정을 조회할 수 있습니다.';
  end if;

  return query
  select
    s.auth_user_id,
    s.organization_type,
    s.department_code,
    d.name,
    s.permission_template_code,
    t.name,
    s.access_scope,
    coalesce((
      select jsonb_agg(jsonb_build_object(
        'project_name', p.project_name,
        'access_start_date', p.access_start_date,
        'access_end_date', p.access_end_date,
        'is_active', p.is_active
      ) order by p.project_name)
      from public.user_project_access_v2 p
      where p.auth_user_id = s.auth_user_id
    ), '[]'::jsonb)
  from public.user_access_settings_v2 s
  join public.departments d on d.code = s.department_code
  join public.permission_templates t on t.code = s.permission_template_code;
end;
$$;

create or replace function public.admin_update_user_access_v2(
  p_user_id uuid,
  p_role text,
  p_organization_type text,
  p_department_code text,
  p_permission_template_code text,
  p_access_scope text,
  p_project_names text[],
  p_project_access jsonb,
  p_account_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before jsonb;
  v_after jsonb;
  v_template public.permission_templates%rowtype;
begin
  if not public.permission_phase2_is_super_admin() then
    raise exception '최고관리자만 회원 권한설정을 변경할 수 있습니다.';
  end if;

  if p_organization_type not in ('본사', '현장', '외부업체') then
    raise exception '사용자 구분이 올바르지 않습니다.';
  end if;

  if p_access_scope not in ('home_project', 'selected', 'all') then
    raise exception '접근현장 범위가 올바르지 않습니다.';
  end if;

  if p_access_scope = 'all' and p_organization_type <> '본사' then
    raise exception '전체현장은 본사 사용자에게만 지정할 수 있습니다.';
  end if;

  if p_access_scope <> 'all' and coalesce(cardinality(p_project_names), 0) = 0 then
    raise exception '접근 현장을 하나 이상 지정해주세요.';
  end if;

  if p_access_scope = 'home_project' and coalesce(cardinality(p_project_names), 0) <> 1 then
    raise exception '소속현장 범위는 현장 한 곳만 지정해야 합니다.';
  end if;

  if not exists (
    select 1 from public.departments
    where code = p_department_code and is_active = true
  ) then
    raise exception '선택한 부서를 찾을 수 없습니다.';
  end if;

  select * into v_template
  from public.permission_templates
  where code = p_permission_template_code and is_active = true;

  if not found then
    raise exception '선택한 권한 템플릿을 찾을 수 없습니다.';
  end if;

  if v_template.organization_type not in ('공통', p_organization_type) then
    raise exception '사용자 구분과 권한 템플릿이 일치하지 않습니다.';
  end if;

  if v_template.department_code is not null
     and v_template.department_code <> p_department_code then
    raise exception '부서와 권한 템플릿이 일치하지 않습니다.';
  end if;

  select jsonb_build_object(
    'settings', to_jsonb(s),
    'projects', coalesce((
      select jsonb_agg(to_jsonb(p) order by p.project_name)
      from public.user_project_access_v2 p
      where p.auth_user_id = p_user_id
    ), '[]'::jsonb)
  ) into v_before
  from public.user_access_settings_v2 s
  where s.auth_user_id = p_user_id;

  perform public.admin_update_user_account_projects(
    p_user_id => p_user_id,
    p_role => p_role,
    p_organization_type => p_organization_type,
    p_project_names => case
      when p_access_scope = 'all' then array['전체현장']::text[]
      else p_project_names
    end,
    p_account_status => p_account_status
  );

  insert into public.user_access_settings_v2 (
    auth_user_id,
    organization_type,
    department_code,
    permission_template_code,
    access_scope,
    updated_at,
    updated_by
  ) values (
    p_user_id,
    p_organization_type,
    p_department_code,
    p_permission_template_code,
    p_access_scope,
    now(),
    auth.uid()
  )
  on conflict (auth_user_id) do update
  set organization_type = excluded.organization_type,
      department_code = excluded.department_code,
      permission_template_code = excluded.permission_template_code,
      access_scope = excluded.access_scope,
      updated_at = now(),
      updated_by = auth.uid();

  delete from public.user_project_access_v2
  where auth_user_id = p_user_id;

  if p_access_scope <> 'all' then
    insert into public.user_project_access_v2 (
      auth_user_id,
      project_name,
      access_start_date,
      access_end_date,
      is_active,
      updated_at
    )
    select distinct on (trim(item->>'project_name'))
      p_user_id,
      trim(item->>'project_name'),
      nullif(item->>'access_start_date', '')::date,
      nullif(item->>'access_end_date', '')::date,
      coalesce((item->>'is_active')::boolean, true),
      now()
    from jsonb_array_elements(coalesce(p_project_access, '[]'::jsonb)) item
    where trim(coalesce(item->>'project_name', '')) <> ''
      and trim(item->>'project_name') = any(p_project_names)
    order by trim(item->>'project_name');

    insert into public.user_project_access_v2 (
      auth_user_id,
      project_name,
      is_active,
      updated_at
    )
    select p_user_id, project_name, true, now()
    from unnest(p_project_names) project_name
    where trim(coalesce(project_name, '')) <> ''
      and not exists (
        select 1 from public.user_project_access_v2 current_access
        where current_access.auth_user_id = p_user_id
          and current_access.project_name = project_name
      );
  end if;

  select jsonb_build_object(
    'organization_type', s.organization_type,
    'department_code', s.department_code,
    'permission_template_code', s.permission_template_code,
    'access_scope', s.access_scope,
    'projects', coalesce((
      select jsonb_agg(to_jsonb(p) order by p.project_name)
      from public.user_project_access_v2 p
      where p.auth_user_id = p_user_id
    ), '[]'::jsonb)
  ) into v_after
  from public.user_access_settings_v2 s
  where s.auth_user_id = p_user_id;

  insert into public.user_access_audit_log_v2
    (target_user_id, changed_by, before_value, after_value)
  values (p_user_id, auth.uid(), v_before, v_after);
end;
$$;

insert into public.user_access_settings_v2 (
  auth_user_id,
  organization_type,
  department_code,
  permission_template_code,
  access_scope
)
select
  up.auth_user_id,
  case when up.organization_type = '본사' then '본사' else '현장' end,
  'construction',
  case
    when lower(regexp_replace(coalesce(up.role, ''), '[[:space:]_-]+', '', 'g'))
      in ('최고관리자', 'superadmin', 'masteradmin') then 'super_admin'
    when up.organization_type = '본사' then 'hq_construction'
    when lower(regexp_replace(coalesce(up.role, ''), '[[:space:]_-]+', '', 'g'))
      in ('관리자', 'admin', 'administrator') then 'site_manager'
    else 'site_construction'
  end,
  case
    when lower(regexp_replace(coalesce(up.role, ''), '[[:space:]_-]+', '', 'g'))
      in ('최고관리자', 'superadmin', 'masteradmin') then 'all'
    when trim(coalesce(up.project_name, '')) = '전체현장' then 'all'
    when up.organization_type = '현장' then 'home_project'
    else 'selected'
  end
from public.user_profiles up
join auth.users au on au.id = up.auth_user_id
where up.auth_user_id is not null
on conflict (auth_user_id) do nothing;

insert into public.user_project_access_v2 (auth_user_id, project_name)
select up.auth_user_id, trim(up.project_name)
from public.user_profiles up
join public.user_access_settings_v2 s on s.auth_user_id = up.auth_user_id
where s.access_scope <> 'all'
  and trim(coalesce(up.project_name, '')) not in ('', '본사', '전체현장')
on conflict (auth_user_id, project_name) do nothing;

do $$
declare
  v_project_names_type text;
begin
  select c.udt_name
    into v_project_names_type
    from information_schema.columns c
    where table_schema = 'public'
      and table_name = 'user_profiles'
      and column_name = 'project_names';

  if v_project_names_type = '_text' then
    execute $copy$
      insert into public.user_project_access_v2 (auth_user_id, project_name)
      select up.auth_user_id, trim(project_name)
      from public.user_profiles up
      cross join lateral unnest(up.project_names) project_name
      join public.user_access_settings_v2 s on s.auth_user_id = up.auth_user_id
      where s.access_scope <> 'all'
        and trim(coalesce(project_name, '')) not in ('', '본사', '전체현장')
      on conflict (auth_user_id, project_name) do nothing
    $copy$;
  elsif v_project_names_type = 'jsonb' then
    execute $copy$
      insert into public.user_project_access_v2 (auth_user_id, project_name)
      select up.auth_user_id, trim(project_name)
      from public.user_profiles up
      cross join lateral jsonb_array_elements_text(up.project_names) project_name
      join public.user_access_settings_v2 s on s.auth_user_id = up.auth_user_id
      where s.access_scope <> 'all'
        and trim(coalesce(project_name, '')) not in ('', '본사', '전체현장')
      on conflict (auth_user_id, project_name) do nothing
    $copy$;
  end if;
end;
$$;

alter table public.departments enable row level security;
alter table public.permission_definitions enable row level security;
alter table public.permission_templates enable row level security;
alter table public.template_menu_levels enable row level security;
alter table public.template_permissions enable row level security;
alter table public.user_access_settings_v2 enable row level security;
alter table public.user_project_access_v2 enable row level security;
alter table public.user_access_audit_log_v2 enable row level security;

revoke all on public.departments from anon, authenticated;
revoke all on public.permission_definitions from anon, authenticated;
revoke all on public.permission_templates from anon, authenticated;
revoke all on public.template_menu_levels from anon, authenticated;
revoke all on public.template_permissions from anon, authenticated;
revoke all on public.user_access_settings_v2 from anon, authenticated;
revoke all on public.user_project_access_v2 from anon, authenticated;
revoke all on public.user_access_audit_log_v2 from anon, authenticated;

revoke all on function public.permission_phase2_is_super_admin() from public;
revoke all on function public.admin_get_access_catalog_v2() from public;
revoke all on function public.admin_list_user_access_v2() from public;
revoke all on function public.admin_update_user_access_v2(uuid, text, text, text, text, text, text[], jsonb, text) from public;

grant execute on function public.admin_get_access_catalog_v2() to authenticated;
grant execute on function public.admin_list_user_access_v2() to authenticated;
grant execute on function public.admin_update_user_access_v2(uuid, text, text, text, text, text, text[], jsonb, text) to authenticated;

commit;
