-- 사내시스템 v52.07 누적배포 SQL
-- 기준 운영 버전: v52.00.2
-- 포함 DB 변경: v52.03.1 회원계정 영구삭제 + v52.04 Main 주요일정
-- 이 파일 하나를 Supabase SQL Editor에서 처음부터 끝까지 실행하면 됩니다.

-- 사내시스템 v52.03.1
-- 최고관리자 전용 회원 계정 영구삭제 기능
-- approval_steps_acted_by_user_id_fkey 오류 수정
-- 실행 위치: Supabase Dashboard > SQL Editor

begin;

create table if not exists public.deleted_user_account_audit (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null,
  target_email text,
  target_name text,
  target_role text,
  deleted_by uuid not null,
  deleted_at timestamptz not null default now()
);

alter table public.deleted_user_account_audit enable row level security;
revoke all on public.deleted_user_account_audit from anon, authenticated;

create or replace function public.admin_delete_user_account(
  p_user_id uuid,
  p_confirmation_email text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_caller_id uuid := auth.uid();
  v_target_email text;
  v_target_name text;
  v_target_role text;
  v_deleted_count integer := 0;
  v_reference record;
  v_reference_count bigint := 0;
  v_blocking_references text[] := array[]::text[];
begin
  if v_caller_id is null then
    raise exception '로그인한 사용자만 계정을 삭제할 수 있습니다.'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.user_profiles caller_profile
    where caller_profile.auth_user_id = v_caller_id
      and coalesce(lower(trim(caller_profile.account_status)), 'active') = 'active'
      and lower(
        regexp_replace(
          coalesce(caller_profile.role, ''),
          '[[:space:]_-]+',
          '',
          'g'
        )
      ) in ('최고관리자', 'superadmin', 'masteradmin')
  ) then
    raise exception '최고관리자만 회원 계정을 삭제할 수 있습니다.'
      using errcode = '42501';
  end if;

  if p_user_id is null then
    raise exception '삭제할 회원 계정을 확인할 수 없습니다.';
  end if;

  if p_user_id = v_caller_id then
    raise exception '현재 로그인한 본인 계정은 삭제할 수 없습니다.';
  end if;

  select
    auth_user.email,
    target_profile.manager_name,
    target_profile.role
  into
    v_target_email,
    v_target_name,
    v_target_role
  from auth.users auth_user
  left join public.user_profiles target_profile
    on target_profile.auth_user_id = auth_user.id
  where auth_user.id = p_user_id;

  if not found then
    raise exception '삭제할 회원 계정을 찾을 수 없습니다.';
  end if;

  if lower(
    regexp_replace(
      coalesce(v_target_role, ''),
      '[[:space:]_-]+',
      '',
      'g'
    )
  ) in ('최고관리자', 'superadmin', 'masteradmin') then
    raise exception '최고관리자 계정은 회원관리 화면에서 삭제할 수 없습니다.';
  end if;

  if lower(trim(coalesce(p_confirmation_email, '')))
     is distinct from lower(trim(coalesce(v_target_email, ''))) then
    raise exception '삭제 확인 이메일이 대상 계정과 일치하지 않습니다.';
  end if;

  insert into public.deleted_user_account_audit (
    target_user_id,
    target_email,
    target_name,
    target_role,
    deleted_by
  ) values (
    p_user_id,
    v_target_email,
    v_target_name,
    v_target_role,
    v_caller_id
  );

  -- 대상자가 과거에 다른 회원 권한을 수정한 기록은 작성자를 비워 보존합니다.
  update public.user_access_settings_v2
  set updated_by = null
  where updated_by = p_user_id;

  update public.user_permission_overrides_v2
  set updated_by = null
  where updated_by = p_user_id;

  update public.user_special_permissions_v2
  set updated_by = null
  where updated_by = p_user_id;

  update public.user_access_audit_log_v2
  set changed_by = null
  where changed_by = p_user_id;

  -- 회원 전용 권한 데이터만 정리합니다. 업무 문서·일보·공정 데이터는 삭제하지 않습니다.
  delete from public.user_access_audit_log_v2
  where target_user_id = p_user_id;

  delete from public.user_special_permissions_v2
  where auth_user_id = p_user_id;

  delete from public.user_permission_overrides_v2
  where auth_user_id = p_user_id;

  delete from public.user_project_access_v2
  where auth_user_id = p_user_id;

  delete from public.user_access_settings_v2
  where auth_user_id = p_user_id;

  delete from public.user_profiles
  where auth_user_id = p_user_id;

  -- 업무·결재 이력에 남아 있는 인증 사용자 참조는 행을 삭제하지 않고 연결만 비웁니다.
  -- 예: approval_steps.acted_by_user_id
  -- 이름·직급·결재시각·의견·문서 내용 등 스냅샷 이력은 그대로 보존됩니다.
  for v_reference in
    select
      reference_namespace.nspname as schema_name,
      reference_table.relname as table_name,
      reference_column.attname as column_name,
      reference_column.attnotnull as is_not_null,
      reference_constraint.conname as constraint_name
    from pg_catalog.pg_constraint reference_constraint
    join pg_catalog.pg_class reference_table
      on reference_table.oid = reference_constraint.conrelid
    join pg_catalog.pg_namespace reference_namespace
      on reference_namespace.oid = reference_table.relnamespace
    join pg_catalog.pg_attribute reference_column
      on reference_column.attrelid = reference_constraint.conrelid
     and reference_column.attnum = reference_constraint.conkey[1]
    join pg_catalog.pg_attribute target_column
      on target_column.attrelid = reference_constraint.confrelid
     and target_column.attnum = reference_constraint.confkey[1]
    where reference_constraint.contype = 'f'
      and reference_constraint.confrelid = 'auth.users'::regclass
      and reference_namespace.nspname = 'public'
      and pg_catalog.array_length(reference_constraint.conkey, 1) = 1
      and pg_catalog.array_length(reference_constraint.confkey, 1) = 1
      and target_column.attname = 'id'
  loop
    execute format(
      'select count(*) from %I.%I where %I = $1',
      v_reference.schema_name,
      v_reference.table_name,
      v_reference.column_name
    )
    into v_reference_count
    using p_user_id;

    if v_reference_count = 0 then
      continue;
    end if;

    if v_reference.is_not_null then
      v_blocking_references := pg_catalog.array_append(
        v_blocking_references,
        format(
          '%I.%I.%I(%s건)',
          v_reference.schema_name,
          v_reference.table_name,
          v_reference.column_name,
          v_reference_count
        )
      );
    else
      execute format(
        'update %I.%I set %I = null where %I = $1',
        v_reference.schema_name,
        v_reference.table_name,
        v_reference.column_name,
        v_reference.column_name
      )
      using p_user_id;
    end if;
  end loop;

  if pg_catalog.array_length(v_blocking_references, 1) is not null then
    raise exception
      '계정이 필수 업무 데이터에 연결되어 있어 삭제할 수 없습니다. 먼저 정리할 항목: %',
      pg_catalog.array_to_string(v_blocking_references, ', ');
  end if;

  delete from auth.users
  where id = p_user_id;

  get diagnostics v_deleted_count = row_count;

  if v_deleted_count <> 1 then
    raise exception '인증 계정을 삭제하지 못했습니다.';
  end if;

  return jsonb_build_object(
    'deleted_user_id', p_user_id,
    'deleted_email', v_target_email,
    'deleted_name', v_target_name,
    'deleted_at', now()
  );
end;
$$;

revoke all on function public.admin_delete_user_account(uuid, text) from public;
revoke all on function public.admin_delete_user_account(uuid, text) from anon;
grant execute on function public.admin_delete_user_account(uuid, text) to authenticated;

commit;


-- ============================================================
-- 다음 단계
-- ============================================================

-- 사내시스템 v52.04
-- Main 화면 월간 주요 이슈 및 전체현장 공유 권한

begin;

insert into public.permission_definitions (
  permission_key,
  area_code,
  area_label,
  menu_code,
  menu_label,
  action_code,
  action_label,
  action_rank,
  is_sensitive,
  is_preparing
)
values (
  'common.main.calendar_issue_global_share',
  'common',
  '공통·조직',
  'main',
  'Main',
  'calendar_issue_global_share',
  '캘린더 이슈 전체현장 공유',
  95,
  true,
  false
)
on conflict (permission_key) do update
set area_code = excluded.area_code,
    area_label = excluded.area_label,
    menu_code = excluded.menu_code,
    menu_label = excluded.menu_label,
    action_code = excluded.action_code,
    action_label = excluded.action_label,
    action_rank = excluded.action_rank,
    is_sensitive = excluded.is_sensitive,
    is_preparing = excluded.is_preparing;

insert into public.template_permissions (
  template_code,
  permission_key,
  is_granted
)
values (
  'super_admin',
  'common.main.calendar_issue_global_share',
  true
)
on conflict (template_code, permission_key) do update
set is_granted = true;

create table if not exists public.main_calendar_issues (
  id bigint generated by default as identity primary key,
  project_name text not null,
  issue_date date not null,
  content text not null,
  share_all_projects boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  author_name text not null default '',
  created_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint main_calendar_issues_content_check
    check (char_length(trim(content)) between 1 and 1000)
);

create index if not exists idx_main_calendar_issues_project_month
  on public.main_calendar_issues(project_name, issue_date, id);

create index if not exists idx_main_calendar_issues_shared_month
  on public.main_calendar_issues(issue_date, id)
  where share_all_projects = true;

alter table public.main_calendar_issues enable row level security;
revoke all on public.main_calendar_issues from anon, authenticated;

create or replace function public.main_calendar_issue_can_access_project(
  p_project_name text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    trim(coalesce(p_project_name, '')) <> ''
    and exists (
      select 1
      from public.user_profiles up
      where up.auth_user_id = auth.uid()
        and coalesce(lower(trim(up.account_status)), 'active') = 'active'
    )
    and (
      public.permission_phase2_is_super_admin()
      or exists (
        select 1
        from public.user_access_settings_v2 settings
        where settings.auth_user_id = auth.uid()
          and settings.access_scope = 'all'
      )
      or exists (
        select 1
        from public.user_project_access_v2 project_access
        where project_access.auth_user_id = auth.uid()
          and project_access.project_name = trim(p_project_name)
          and project_access.is_active = true
          and (
            project_access.access_start_date is null
            or project_access.access_start_date <= current_date
          )
          and (
            project_access.access_end_date is null
            or project_access.access_end_date >= current_date
          )
      )
    );
$$;

create or replace function public.main_calendar_issue_can_share_all_projects(
  p_project_name text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.main_calendar_issue_can_access_project(p_project_name)
    and (
      public.permission_phase2_is_super_admin()
      or exists (
        select 1
        from public.user_special_permissions_v2 special_permission
        where special_permission.auth_user_id = auth.uid()
          and special_permission.permission_key =
            'common.main.calendar_issue_global_share'
      )
    );
$$;

create or replace function public.main_get_calendar_issue_context(
  p_project_name text
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'can_write',
      public.main_calendar_issue_can_access_project(p_project_name),
    'can_share_all_projects',
      public.main_calendar_issue_can_share_all_projects(p_project_name)
  );
$$;

drop function if exists public.main_list_calendar_issues(text, date);

create function public.main_list_calendar_issues(
  p_project_name text,
  p_month_start date
)
returns table (
  id bigint,
  project_name text,
  issue_date date,
  content text,
  share_all_projects boolean,
  author_name text,
  updated_at timestamptz,
  can_edit boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.main_calendar_issue_can_access_project(p_project_name) then
    raise exception '이 현장의 캘린더 주요 이슈를 조회할 권한이 없습니다.';
  end if;

  if p_month_start is null then
    raise exception '조회할 월을 선택해주세요.';
  end if;

  return query
  select
    issue.id,
    issue.project_name,
    issue.issue_date,
    issue.content,
    issue.share_all_projects,
    issue.author_name,
    issue.updated_at,
    (
      public.permission_phase2_is_super_admin()
      or (
        issue.created_by = auth.uid()
        and (
          issue.share_all_projects = false
          or public.main_calendar_issue_can_share_all_projects(
            issue.project_name
          )
        )
      )
    ) as can_edit
  from public.main_calendar_issues issue
  where issue.issue_date >= date_trunc('month', p_month_start)::date
    and issue.issue_date <
      (date_trunc('month', p_month_start) + interval '1 month')::date
    and (
      issue.project_name = trim(p_project_name)
      or issue.share_all_projects = true
    )
  order by issue.issue_date, issue.id;
end;
$$;

create or replace function public.main_save_calendar_issue(
  p_issue_id bigint,
  p_project_name text,
  p_issue_date date,
  p_content text,
  p_share_all_projects boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_issue public.main_calendar_issues%rowtype;
  v_content text := trim(coalesce(p_content, ''));
  v_author_name text;
  v_saved_id bigint;
begin
  if not public.main_calendar_issue_can_access_project(p_project_name) then
    raise exception '이 현장의 캘린더 주요 이슈를 작성할 권한이 없습니다.';
  end if;

  if p_issue_date is null then
    raise exception '이슈 일자를 입력해주세요.';
  end if;

  if char_length(v_content) < 1 or char_length(v_content) > 1000 then
    raise exception '주요 이슈 내용은 1자 이상 1000자 이하로 입력해주세요.';
  end if;

  if coalesce(p_share_all_projects, false)
     and not public.main_calendar_issue_can_share_all_projects(p_project_name) then
    raise exception '전체현장 공유 권한이 없습니다.';
  end if;

  select coalesce(
    nullif(trim(profile.manager_name), ''),
    nullif(trim(profile.email), ''),
    '사용자'
  )
  into v_author_name
  from public.user_profiles profile
  where profile.auth_user_id = auth.uid()
  limit 1;

  if p_issue_id is null then
    insert into public.main_calendar_issues (
      project_name,
      issue_date,
      content,
      share_all_projects,
      created_by,
      author_name,
      updated_by,
      updated_at
    ) values (
      trim(p_project_name),
      p_issue_date,
      v_content,
      coalesce(p_share_all_projects, false),
      auth.uid(),
      coalesce(v_author_name, '사용자'),
      auth.uid(),
      now()
    )
    returning id into v_saved_id;

    return v_saved_id;
  end if;

  select *
  into v_issue
  from public.main_calendar_issues issue
  where issue.id = p_issue_id
  for update;

  if not found then
    raise exception '수정할 주요 이슈를 찾을 수 없습니다.';
  end if;

  if not public.main_calendar_issue_can_access_project(v_issue.project_name) then
    raise exception '이 주요 이슈가 등록된 현장에 접근할 권한이 없습니다.';
  end if;

  if v_issue.created_by is distinct from auth.uid()
     and not public.permission_phase2_is_super_admin() then
    raise exception '본인이 작성한 주요 이슈만 수정할 수 있습니다.';
  end if;

  update public.main_calendar_issues
  set issue_date = p_issue_date,
      content = v_content,
      share_all_projects = coalesce(p_share_all_projects, false),
      updated_by = auth.uid(),
      updated_at = now()
  where id = p_issue_id
  returning id into v_saved_id;

  return v_saved_id;
end;
$$;

create or replace function public.main_delete_calendar_issue(
  p_issue_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_issue public.main_calendar_issues%rowtype;
begin
  select *
  into v_issue
  from public.main_calendar_issues issue
  where issue.id = p_issue_id
  for update;

  if not found then
    raise exception '삭제할 주요 이슈를 찾을 수 없습니다.';
  end if;

  if not public.main_calendar_issue_can_access_project(v_issue.project_name) then
    raise exception '이 주요 이슈가 등록된 현장에 접근할 권한이 없습니다.';
  end if;

  if v_issue.created_by is distinct from auth.uid()
     and not public.permission_phase2_is_super_admin() then
    raise exception '본인이 작성한 주요 이슈만 삭제할 수 있습니다.';
  end if;

  delete from public.main_calendar_issues
  where id = p_issue_id;
end;
$$;

revoke all on function public.main_calendar_issue_can_access_project(text)
  from public;
revoke all on function public.main_calendar_issue_can_share_all_projects(text)
  from public;
revoke all on function public.main_get_calendar_issue_context(text)
  from public;
revoke all on function public.main_list_calendar_issues(text, date)
  from public;
revoke all on function public.main_save_calendar_issue(bigint, text, date, text, boolean)
  from public;
revoke all on function public.main_delete_calendar_issue(bigint)
  from public;

grant execute on function public.main_get_calendar_issue_context(text)
  to authenticated;
grant execute on function public.main_list_calendar_issues(text, date)
  to authenticated;
grant execute on function public.main_save_calendar_issue(bigint, text, date, text, boolean)
  to authenticated;
grant execute on function public.main_delete_calendar_issue(bigint)
  to authenticated;

commit;
