-- 사내시스템 v52.03.1
-- 최고관리자 전용 회원 계정 영구삭제 기능
-- approval_steps_acted_by_user_id_fkey 오류 수정
-- 실행 위치: Supabase Dashboard > SQL Editor

begin;

create table if not exists public.deleted_user_account_audit (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null,
  target_email text,
  target_name text,
  target_role text,
  deleted_by uuid not null,
  deleted_at timestamptz not null default now()
);

alter table public.deleted_user_account_audit enable row level security;
revoke all on public.deleted_user_account_audit from anon, authenticated;

create or replace function public.admin_delete_user_account(
  p_user_id uuid,
  p_confirmation_email text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_caller_id uuid := auth.uid();
  v_target_email text;
  v_target_name text;
  v_target_role text;
  v_deleted_count integer := 0;
  v_reference record;
  v_reference_count bigint := 0;
  v_blocking_references text[] := array[]::text[];
begin
  if v_caller_id is null then
    raise exception '로그인한 사용자만 계정을 삭제할 수 있습니다.'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.user_profiles caller_profile
    where caller_profile.auth_user_id = v_caller_id
      and coalesce(lower(trim(caller_profile.account_status)), 'active') = 'active'
      and lower(
        regexp_replace(
          coalesce(caller_profile.role, ''),
          '[[:space:]_-]+',
          '',
          'g'
        )
      ) in ('최고관리자', 'superadmin', 'masteradmin')
  ) then
    raise exception '최고관리자만 회원 계정을 삭제할 수 있습니다.'
      using errcode = '42501';
  end if;

  if p_user_id is null then
    raise exception '삭제할 회원 계정을 확인할 수 없습니다.';
  end if;

  if p_user_id = v_caller_id then
    raise exception '현재 로그인한 본인 계정은 삭제할 수 없습니다.';
  end if;

  select
    auth_user.email,
    target_profile.manager_name,
    target_profile.role
  into
    v_target_email,
    v_target_name,
    v_target_role
  from auth.users auth_user
  left join public.user_profiles target_profile
    on target_profile.auth_user_id = auth_user.id
  where auth_user.id = p_user_id;

  if not found then
    raise exception '삭제할 회원 계정을 찾을 수 없습니다.';
  end if;

  if lower(
    regexp_replace(
      coalesce(v_target_role, ''),
      '[[:space:]_-]+',
      '',
      'g'
    )
  ) in ('최고관리자', 'superadmin', 'masteradmin') then
    raise exception '최고관리자 계정은 회원관리 화면에서 삭제할 수 없습니다.';
  end if;

  if lower(trim(coalesce(p_confirmation_email, '')))
     is distinct from lower(trim(coalesce(v_target_email, ''))) then
    raise exception '삭제 확인 이메일이 대상 계정과 일치하지 않습니다.';
  end if;

  insert into public.deleted_user_account_audit (
    target_user_id,
    target_email,
    target_name,
    target_role,
    deleted_by
  ) values (
    p_user_id,
    v_target_email,
    v_target_name,
    v_target_role,
    v_caller_id
  );

  -- 대상자가 과거에 다른 회원 권한을 수정한 기록은 작성자를 비워 보존합니다.
  update public.user_access_settings_v2
  set updated_by = null
  where updated_by = p_user_id;

  update public.user_permission_overrides_v2
  set updated_by = null
  where updated_by = p_user_id;

  update public.user_special_permissions_v2
  set updated_by = null
  where updated_by = p_user_id;

  update public.user_access_audit_log_v2
  set changed_by = null
  where changed_by = p_user_id;

  -- 회원 전용 권한 데이터만 정리합니다. 업무 문서·일보·공정 데이터는 삭제하지 않습니다.
  delete from public.user_access_audit_log_v2
  where target_user_id = p_user_id;

  delete from public.user_special_permissions_v2
  where auth_user_id = p_user_id;

  delete from public.user_permission_overrides_v2
  where auth_user_id = p_user_id;

  delete from public.user_project_access_v2
  where auth_user_id = p_user_id;

  delete from public.user_access_settings_v2
  where auth_user_id = p_user_id;

  delete from public.user_profiles
  where auth_user_id = p_user_id;

  -- 업무·결재 이력에 남아 있는 인증 사용자 참조는 행을 삭제하지 않고 연결만 비웁니다.
  -- 예: approval_steps.acted_by_user_id
  -- 이름·직급·결재시각·의견·문서 내용 등 스냅샷 이력은 그대로 보존됩니다.
  for v_reference in
    select
      reference_namespace.nspname as schema_name,
      reference_table.relname as table_name,
      reference_column.attname as column_name,
      reference_column.attnotnull as is_not_null,
      reference_constraint.conname as constraint_name
    from pg_catalog.pg_constraint reference_constraint
    join pg_catalog.pg_class reference_table
      on reference_table.oid = reference_constraint.conrelid
    join pg_catalog.pg_namespace reference_namespace
      on reference_namespace.oid = reference_table.relnamespace
    join pg_catalog.pg_attribute reference_column
      on reference_column.attrelid = reference_constraint.conrelid
     and reference_column.attnum = reference_constraint.conkey[1]
    join pg_catalog.pg_attribute target_column
      on target_column.attrelid = reference_constraint.confrelid
     and target_column.attnum = reference_constraint.confkey[1]
    where reference_constraint.contype = 'f'
      and reference_constraint.confrelid = 'auth.users'::regclass
      and reference_namespace.nspname = 'public'
      and pg_catalog.array_length(reference_constraint.conkey, 1) = 1
      and pg_catalog.array_length(reference_constraint.confkey, 1) = 1
      and target_column.attname = 'id'
  loop
    execute format(
      'select count(*) from %I.%I where %I = $1',
      v_reference.schema_name,
      v_reference.table_name,
      v_reference.column_name
    )
    into v_reference_count
    using p_user_id;

    if v_reference_count = 0 then
      continue;
    end if;

    if v_reference.is_not_null then
      v_blocking_references := pg_catalog.array_append(
        v_blocking_references,
        format(
          '%I.%I.%I(%s건)',
          v_reference.schema_name,
          v_reference.table_name,
          v_reference.column_name,
          v_reference_count
        )
      );
    else
      execute format(
        'update %I.%I set %I = null where %I = $1',
        v_reference.schema_name,
        v_reference.table_name,
        v_reference.column_name,
        v_reference.column_name
      )
      using p_user_id;
    end if;
  end loop;

  if pg_catalog.array_length(v_blocking_references, 1) is not null then
    raise exception
      '계정이 필수 업무 데이터에 연결되어 있어 삭제할 수 없습니다. 먼저 정리할 항목: %',
      pg_catalog.array_to_string(v_blocking_references, ', ');
  end if;

  delete from auth.users
  where id = p_user_id;

  get diagnostics v_deleted_count = row_count;

  if v_deleted_count <> 1 then
    raise exception '인증 계정을 삭제하지 못했습니다.';
  end if;

  return jsonb_build_object(
    'deleted_user_id', p_user_id,
    'deleted_email', v_target_email,
    'deleted_name', v_target_name,
    'deleted_at', now()
  );
end;
$$;

revoke all on function public.admin_delete_user_account(uuid, text) from public;
revoke all on function public.admin_delete_user_account(uuid, text) from anon;
grant execute on function public.admin_delete_user_account(uuid, text) to authenticated;

commit;
