-- 사내시스템 v52.04
-- Main 화면 월간 주요 이슈 및 전체현장 공유 권한

begin;

insert into public.permission_definitions (
  permission_key,
  area_code,
  area_label,
  menu_code,
  menu_label,
  action_code,
  action_label,
  action_rank,
  is_sensitive,
  is_preparing
)
values (
  'common.main.calendar_issue_global_share',
  'common',
  '공통·조직',
  'main',
  'Main',
  'calendar_issue_global_share',
  '캘린더 이슈 전체현장 공유',
  95,
  true,
  false
)
on conflict (permission_key) do update
set area_code = excluded.area_code,
    area_label = excluded.area_label,
    menu_code = excluded.menu_code,
    menu_label = excluded.menu_label,
    action_code = excluded.action_code,
    action_label = excluded.action_label,
    action_rank = excluded.action_rank,
    is_sensitive = excluded.is_sensitive,
    is_preparing = excluded.is_preparing;

insert into public.template_permissions (
  template_code,
  permission_key,
  is_granted
)
values (
  'super_admin',
  'common.main.calendar_issue_global_share',
  true
)
on conflict (template_code, permission_key) do update
set is_granted = true;

create table if not exists public.main_calendar_issues (
  id bigint generated by default as identity primary key,
  project_name text not null,
  issue_date date not null,
  content text not null,
  share_all_projects boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  author_name text not null default '',
  created_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint main_calendar_issues_content_check
    check (char_length(trim(content)) between 1 and 1000)
);

create index if not exists idx_main_calendar_issues_project_month
  on public.main_calendar_issues(project_name, issue_date, id);

create index if not exists idx_main_calendar_issues_shared_month
  on public.main_calendar_issues(issue_date, id)
  where share_all_projects = true;

alter table public.main_calendar_issues enable row level security;
revoke all on public.main_calendar_issues from anon, authenticated;

create or replace function public.main_calendar_issue_can_access_project(
  p_project_name text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    trim(coalesce(p_project_name, '')) <> ''
    and exists (
      select 1
      from public.user_profiles up
      where up.auth_user_id = auth.uid()
        and coalesce(lower(trim(up.account_status)), 'active') = 'active'
    )
    and (
      public.permission_phase2_is_super_admin()
      or exists (
        select 1
        from public.user_access_settings_v2 settings
        where settings.auth_user_id = auth.uid()
          and settings.access_scope = 'all'
      )
      or exists (
        select 1
        from public.user_project_access_v2 project_access
        where project_access.auth_user_id = auth.uid()
          and project_access.project_name = trim(p_project_name)
          and project_access.is_active = true
          and (
            project_access.access_start_date is null
            or project_access.access_start_date <= current_date
          )
          and (
            project_access.access_end_date is null
            or project_access.access_end_date >= current_date
          )
      )
    );
$$;

create or replace function public.main_calendar_issue_can_share_all_projects(
  p_project_name text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.main_calendar_issue_can_access_project(p_project_name)
    and (
      public.permission_phase2_is_super_admin()
      or exists (
        select 1
        from public.user_special_permissions_v2 special_permission
        where special_permission.auth_user_id = auth.uid()
          and special_permission.permission_key =
            'common.main.calendar_issue_global_share'
      )
    );
$$;

create or replace function public.main_get_calendar_issue_context(
  p_project_name text
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'can_write',
      public.main_calendar_issue_can_access_project(p_project_name),
    'can_share_all_projects',
      public.main_calendar_issue_can_share_all_projects(p_project_name)
  );
$$;

drop function if exists public.main_list_calendar_issues(text, date);

create function public.main_list_calendar_issues(
  p_project_name text,
  p_month_start date
)
returns table (
  id bigint,
  project_name text,
  issue_date date,
  content text,
  share_all_projects boolean,
  author_name text,
  updated_at timestamptz,
  can_edit boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.main_calendar_issue_can_access_project(p_project_name) then
    raise exception '이 현장의 캘린더 주요 이슈를 조회할 권한이 없습니다.';
  end if;

  if p_month_start is null then
    raise exception '조회할 월을 선택해주세요.';
  end if;

  return query
  select
    issue.id,
    issue.project_name,
    issue.issue_date,
    issue.content,
    issue.share_all_projects,
    issue.author_name,
    issue.updated_at,
    (
      public.permission_phase2_is_super_admin()
      or (
        issue.created_by = auth.uid()
        and (
          issue.share_all_projects = false
          or public.main_calendar_issue_can_share_all_projects(
            issue.project_name
          )
        )
      )
    ) as can_edit
  from public.main_calendar_issues issue
  where issue.issue_date >= date_trunc('month', p_month_start)::date
    and issue.issue_date <
      (date_trunc('month', p_month_start) + interval '1 month')::date
    and (
      issue.project_name = trim(p_project_name)
      or issue.share_all_projects = true
    )
  order by issue.issue_date, issue.id;
end;
$$;

create or replace function public.main_save_calendar_issue(
  p_issue_id bigint,
  p_project_name text,
  p_issue_date date,
  p_content text,
  p_share_all_projects boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_issue public.main_calendar_issues%rowtype;
  v_content text := trim(coalesce(p_content, ''));
  v_author_name text;
  v_saved_id bigint;
begin
  if not public.main_calendar_issue_can_access_project(p_project_name) then
    raise exception '이 현장의 캘린더 주요 이슈를 작성할 권한이 없습니다.';
  end if;

  if p_issue_date is null then
    raise exception '이슈 일자를 입력해주세요.';
  end if;

  if char_length(v_content) < 1 or char_length(v_content) > 1000 then
    raise exception '주요 이슈 내용은 1자 이상 1000자 이하로 입력해주세요.';
  end if;

  if coalesce(p_share_all_projects, false)
     and not public.main_calendar_issue_can_share_all_projects(p_project_name) then
    raise exception '전체현장 공유 권한이 없습니다.';
  end if;

  select coalesce(
    nullif(trim(profile.manager_name), ''),
    nullif(trim(profile.email), ''),
    '사용자'
  )
  into v_author_name
  from public.user_profiles profile
  where profile.auth_user_id = auth.uid()
  limit 1;

  if p_issue_id is null then
    insert into public.main_calendar_issues (
      project_name,
      issue_date,
      content,
      share_all_projects,
      created_by,
      author_name,
      updated_by,
      updated_at
    ) values (
      trim(p_project_name),
      p_issue_date,
      v_content,
      coalesce(p_share_all_projects, false),
      auth.uid(),
      coalesce(v_author_name, '사용자'),
      auth.uid(),
      now()
    )
    returning id into v_saved_id;

    return v_saved_id;
  end if;

  select *
  into v_issue
  from public.main_calendar_issues issue
  where issue.id = p_issue_id
  for update;

  if not found then
    raise exception '수정할 주요 이슈를 찾을 수 없습니다.';
  end if;

  if not public.main_calendar_issue_can_access_project(v_issue.project_name) then
    raise exception '이 주요 이슈가 등록된 현장에 접근할 권한이 없습니다.';
  end if;

  if v_issue.created_by is distinct from auth.uid()
     and not public.permission_phase2_is_super_admin() then
    raise exception '본인이 작성한 주요 이슈만 수정할 수 있습니다.';
  end if;

  update public.main_calendar_issues
  set issue_date = p_issue_date,
      content = v_content,
      share_all_projects = coalesce(p_share_all_projects, false),
      updated_by = auth.uid(),
      updated_at = now()
  where id = p_issue_id
  returning id into v_saved_id;

  return v_saved_id;
end;
$$;

create or replace function public.main_delete_calendar_issue(
  p_issue_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_issue public.main_calendar_issues%rowtype;
begin
  select *
  into v_issue
  from public.main_calendar_issues issue
  where issue.id = p_issue_id
  for update;

  if not found then
    raise exception '삭제할 주요 이슈를 찾을 수 없습니다.';
  end if;

  if not public.main_calendar_issue_can_access_project(v_issue.project_name) then
    raise exception '이 주요 이슈가 등록된 현장에 접근할 권한이 없습니다.';
  end if;

  if v_issue.created_by is distinct from auth.uid()
     and not public.permission_phase2_is_super_admin() then
    raise exception '본인이 작성한 주요 이슈만 삭제할 수 있습니다.';
  end if;

  delete from public.main_calendar_issues
  where id = p_issue_id;
end;
$$;

revoke all on function public.main_calendar_issue_can_access_project(text)
  from public;
revoke all on function public.main_calendar_issue_can_share_all_projects(text)
  from public;
revoke all on function public.main_get_calendar_issue_context(text)
  from public;
revoke all on function public.main_list_calendar_issues(text, date)
  from public;
revoke all on function public.main_save_calendar_issue(bigint, text, date, text, boolean)
  from public;
revoke all on function public.main_delete_calendar_issue(bigint)
  from public;

grant execute on function public.main_get_calendar_issue_context(text)
  to authenticated;
grant execute on function public.main_list_calendar_issues(text, date)
  to authenticated;
grant execute on function public.main_save_calendar_issue(bigint, text, date, text, boolean)
  to authenticated;
grant execute on function public.main_delete_calendar_issue(bigint)
  to authenticated;

commit;
